# Generated by Django 5.0.4 on 2024-06-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='tarkibi',
            field=models.CharField(max_length=255),
        ),
    ]
